class PerformanceCoachEngine {
  constructor({missionLogs=[],exerciseLogs=[],golfLogs=[],softballLogs=[],nutritionLogs=[],schedule={},today=new Date()}){this.missionLogs=missionLogs;this.exerciseLogs=exerciseLogs;this.golfLogs=golfLogs;this.softballLogs=softballLogs;this.nutritionLogs=nutritionLogs;this.schedule=schedule;this.today=today}
  avg(v){const c=v.filter(x=>Number.isFinite(Number(x)));return c.length?c.reduce((a,b)=>a+Number(b),0)/c.length:0}
  slope(v){const c=v.filter(x=>Number.isFinite(Number(x)));return c.length<2?0:(c.at(-1)-c[0])/(c.length-1)}
  metrics(){const m=this.missionLogs.slice(-7),g=this.golfLogs.slice(-6),s=this.softballLogs.slice(-6),e=this.exerciseLogs.slice(-16),n=this.nutritionLogs.slice(-7);return{avgIron:this.avg(m.map(x=>x.ironScore||0)),avgSleep:this.avg(m.map(x=>x.sleep||0)),avgReadiness:this.avg(m.map(x=>x.readinessScore||0)),avgWater:this.avg(m.map(x=>x.water||0)),weightSlope:this.slope(m.map(x=>x.weight||0).filter(x=>x>0)),golfContact:this.avg(g.map(x=>x.contact||0)),golfTrend:this.slope(g.map(x=>x.contact||0)),golfConfidence:this.avg(g.map(x=>x.confidence||0)),softballConfidence:this.avg(s.map(x=>x.confidence||0)),softballTrend:this.slope(s.map(x=>x.confidence||0)),armFatigue:this.avg(s.map(x=>x.armFatigue||0)),shoulderPain:this.avg(s.map(x=>x.shoulderPain||0)),exercisePain:e.filter(x=>x.pain).length,avgRpe:this.avg(e.map(x=>x.rpe||0)),avgTechnique:this.avg(e.map(x=>x.technique||0)),nutritionCompliance:n.length?this.avg(n.map(x=>((x.mealsCompleted||0)/3*70)+(x.onPlan?30:0))):0,daysLogged:m.length}}
  causes(){const m=this.metrics(),c=[];const add=(category,severity,title,explanation,evidence)=>c.push({category,severity,title,explanation,evidence});
    if(m.avgSleep>0&&m.avgSleep<6)add('Recovery','critical','Severe sleep debt',`Average sleep is ${m.avgSleep.toFixed(1)} hours. Recovery and motor learning are likely impaired.`,['Low sleep','Higher fatigue risk']);else if(m.avgSleep>0&&m.avgSleep<7)add('Recovery','warning','Sleep is limiting adaptation',`Average sleep is ${m.avgSleep.toFixed(1)} hours. Progress conservatively.`,['Suboptimal sleep duration']);
    if(m.avgReadiness>0&&m.avgReadiness<70)add('Recovery','critical','Readiness is suppressed',`Average readiness is ${Math.round(m.avgReadiness)}. Current workload is not being fully absorbed.`,['Low readiness','Accumulated fatigue']);
    if(m.avgIron>0&&m.avgIron<70)add('Execution','warning','Daily execution is inconsistent',`Average Iron Score is ${Math.round(m.avgIron)}. Missed fundamentals are limiting progress.`,['Incomplete missions']);
    if(m.golfContact>0&&m.golfContact<68)add('Golf','warning','Contact quality is below target',`Average contact is ${Math.round(m.golfContact)}%. Return to slower checkpoint work.`,['Low contact percentage']);
    if(m.golfTrend<-2)add('Golf','warning','Golf contact is trending down','Fatigue, excessive swing thoughts, or moving too quickly may be contributing.',['Negative contact trend']);
    if(m.armFatigue>=6||m.shoulderPain>=4)add('Softball','critical','Arm load is too high',`Arm fatigue is ${m.armFatigue.toFixed(1)} and shoulder pain is ${m.shoulderPain.toFixed(1)}.`,['Elevated arm fatigue','Shoulder discomfort']);
    if(m.softballTrend<-.4)add('Softball','warning','Softball confidence is declining','Reduce drill complexity and return to successful repetitions.',['Negative confidence trend']);
    if(m.exercisePain>0)add('Strength','critical','Pain has been recorded in training',`${m.exercisePain} recent exercise entries included pain.`,['Pain flag']);
    if(m.avgRpe>8.5)add('Strength','warning','Training effort is too consistently high',`Average RPE is ${m.avgRpe.toFixed(1)}.`,['High average RPE']);
    if(m.avgTechnique>0&&m.avgTechnique<7.5)add('Strength','warning','Technique quality is limiting progression',`Average technique score is ${m.avgTechnique.toFixed(1)}.`,['Technique below standard']);
    if(m.nutritionCompliance>0&&m.nutritionCompliance<75)add('Nutrition','warning','Nutrition execution is inconsistent',`Estimated nutrition compliance is ${Math.round(m.nutritionCompliance)}%.`,['Missed meals or unplanned intake']);
    if(m.weightSlope<-.35)add('Nutrition','warning','Weight may be falling too quickly','Performance and recovery should be monitored closely.',['Steep negative weight trend']);
    if(!c.length)add('Overall','good','No major limiting factor identified','Continue the plan without adding unnecessary complexity.',['Stable trends']);return c}
  actions(){const a=[];const add=(priority,category,title,instruction,metric)=>a.push({priority,category,title,instruction,metric});for(const c of this.causes()){if(c.title.toLowerCase().includes('sleep'))add(1,'Recovery','Protect the next sleep window','Remove optional volume and prioritize a full sleep opportunity.','Sleep');if(c.title.includes('Readiness'))add(1,'Recovery','Use reduced volume','Reduce total training volume by 20–40% until readiness improves.','Readiness');if(c.category==='Execution')add(2,'Execution','Complete the minimum mission','Faith, readiness, training minimum, meals, hydration, and review come first.','Iron Score');if(c.category==='Golf')add(2,'Golf','Return to contact fundamentals','Use half-swings, chest-start takeaway, and shaft-parallel checkpoints.','Golf contact');if(c.title.includes('Arm load'))add(1,'Softball','Stop hard throwing','Use arm care, dry footwork, and hitting mechanics only.','Arm health');if(c.title.includes('confidence'))add(2,'Softball','Reduce drill complexity','Use successful repetitions before game-speed variability.','Confidence');if(c.title.includes('Pain'))add(1,'Strength','Regress painful movements','Remove or regress any exercise that produces pain.','Pain');if(c.title.includes('effort'))add(2,'Strength','Cap RPE at 8','Leave at least two clean repetitions in reserve.','RPE');if(c.title.includes('Technique'))add(2,'Strength','Hold current resistance','Do not progress until technique is 8/10 or better.','Technique');if(c.category==='Nutrition'&&c.title.includes('inconsistent'))add(2,'Nutrition','Improve adherence first','Complete current portions consistently before another adjustment.','Compliance');if(c.title.includes('too quickly'))add(1,'Nutrition','Increase performance fuel slightly','Add a small carbohydrate portion around training and reassess.','Weight trend')}
    if(!a.length)add(3,'Overall','Continue the current operation','Maintain the plan and avoid unnecessary volume.','Stability');const seen=new Set();return a.sort((x,y)=>x.priority-y.priority).filter(x=>{const k=x.category+'|'+x.title;if(seen.has(k))return false;seen.add(k);return true}).slice(0,6)}
  dataConfidence(){const m=this.metrics();let s=0;if(m.daysLogged>=5)s+=30;if(this.golfLogs.length>=3)s+=15;if(this.softballLogs.length>=3)s+=15;if(this.exerciseLogs.length>=6)s+=15;if(this.nutritionLogs.length>=4)s+=15;if(this.missionLogs.some(x=>x.weight>0))s+=10;return Math.min(100,s)}
  dailyBrief(){const m=this.metrics(),a=this.actions(),p=a[0],s=a[1]||null;return{headline:p?.title||'Continue the operation',summary:p?.instruction||'Execute the current plan.',primary:p,secondary:s,metrics:m,confidence:this.dataConfidence(),questions:this.answerBank()}}
  answerBank(){const c=this.causes(),by=k=>c.filter(x=>x.category===k);return{iron:by('Execution')[0]?.explanation||'Your Iron Score is not showing a major execution problem.',golf:by('Golf')[0]?.explanation||'Golf performance is not showing a major negative signal.',recovery:by('Recovery')[0]?.explanation||'Recovery appears stable from available data.',tomorrow:this.actions()[0]?.instruction||'Continue the current plan.'}}
}