(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.IronNutrition=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clamp=(n,a=0,b=Infinity)=>Math.max(a,Math.min(b,Number(n)||0));
const round=(n,step=1)=>Math.round((Number(n)||0)/step)*step;
function normalizeProfile(profile={}){return {sex:profile.sex==='female'?'female':'male',age:clamp(profile.age||35,18,90),heightIn:clamp(profile.heightIn||72,48,84),weightLb:clamp(profile.weightLb||220,80,500),bodyFat:clamp(profile.bodyFat||30,3,70),targetWeightLb:clamp(profile.targetWeightLb||200,80,500),mode:['cut','maintain','recomp','gain'].includes(profile.mode)?profile.mode:'cut',activity:['low','moderate','high','very-high'].includes(profile.activity)?profile.activity:'moderate',weeklyChangePct:clamp(profile.weeklyChangePct||0.6,0.1,1.5)};}
function leanMassLb(p){p=normalizeProfile(p);return p.weightLb*(1-p.bodyFat/100);}
function bmr(profile){const p=normalizeProfile(profile),kg=p.weightLb*.453592,cm=p.heightIn*2.54;return Math.round(10*kg+6.25*cm-5*p.age+(p.sex==='male'?5:-161));}
function targets(profile={},context={}){const p=normalizeProfile(profile),factors={low:1.3,moderate:1.5,high:1.7,'very-high':1.85};let calories=bmr(p)*factors[p.activity];const weekly=p.weightLb*(p.weeklyChangePct/100)*3500/7;if(p.mode==='cut')calories-=weekly;else if(p.mode==='gain')calories+=Math.min(weekly,450);else if(p.mode==='recomp')calories-=150;
const training=context.trainingDay!==false,readiness=clamp(context.readiness||70,0,100),event=context.eventDay===true;if(training)calories+=100;if(event)calories+=250;if(readiness<50)calories-=100;calories=round(Math.max(calories,1400),25);
const protein=round(Math.max(leanMassLb(p)*1.0,p.weightLb*.75),5);const fat=round(Math.max(p.weightLb*.28,50),5);const carbs=round(Math.max((calories-protein*4-fat*9)/4,75),5);return {calories,protein,carbs,fat,fiber:Math.max(25,round(calories/1000*14)),water:round(Math.max(96,p.weightLb*.55),8),sodium:event||training?3000:2300,potassium:3500};}
function compliance(log={},target={}){const keys=['calories','protein','carbs','fat','fiber','water'];const score=keys.reduce((sum,k)=>{const v=Number(log[k])||0,t=Number(target[k])||0;if(!t)return sum;const ratio=v/t;const component=k==='calories'?Math.max(0,100-Math.abs(1-ratio)*140):Math.min(100,ratio*100);return sum+component;},0)/keys.length;return Math.round(score||0);}
function gaps(log={},target={}){return ['protein','carbs','fat','fiber','water','calories'].map(k=>({key:k,remaining:Math.max(0,round((Number(target[k])||0)-(Number(log[k])||0),k==='calories'?25:1))})).filter(x=>x.remaining>0);}
function recommendation(log={},target={},context={}){const g=Object.fromEntries(gaps(log,target).map(x=>[x.key,x.remaining]));if(g.protein>=40)return {title:'Close the protein gap',detail:`Prioritize a meal with about ${round(g.protein,5)} g protein. Pair it with a familiar carbohydrate source if training remains.`,type:'protein'};if(g.water>=24)return {title:'Hydration is the next lever',detail:`Drink ${round(Math.min(g.water,32),8)} oz over the next two hours${context.eventDay?' with electrolytes':''}.`,type:'water'};if(g.carbs>=60&&context.trainingDay!==false)return {title:'Fuel performance',detail:`Add approximately ${round(Math.min(g.carbs,80),5)} g carbohydrate around training.`,type:'carbs'};if((Number(log.calories)||0)>(Number(target.calories)||0)*1.1)return {title:'Protect the calorie target',detail:'Choose lean protein, vegetables, and calorie-free fluids for the rest of the day.',type:'calories'};return {title:'Nutrition is on course',detail:'Complete the planned meals, preserve hydration, and avoid unnecessary changes.',type:'aligned'};}
function mealSuggestion(log={},target={},library=[]){const rec=recommendation(log,target,{trainingDay:true});const defaults=[{name:'Beef, rice & broccoli',protein:50,carbs:55,fat:18,calories:590,tags:['protein','carbs']},{name:'Greek yogurt protein bowl',protein:45,carbs:45,fat:5,calories:405,tags:['protein']},{name:'Lean protein recovery plate',protein:55,carbs:65,fat:12,calories:590,tags:['protein','carbs']}];const meals=library.length?library:defaults;return meals.find(m=>(m.tags||[]).includes(rec.type))||meals[0];}
return {normalizeProfile,leanMassLb,bmr,targets,compliance,gaps,recommendation,mealSuggestion};
});
