(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.IronNutrition=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clamp=(n,a=0,b=Infinity)=>Math.max(a,Math.min(b,Number(n)||0));
const round=(n,step=1)=>Math.round((Number(n)||0)/step)*step;
const MEAL_KEYS=['calories','protein','carbs','fat','fiber'];
const ingredient=(name,quantity,unit,category='Other',cost=0)=>({name,quantity,unit,category,cost});
const DEFAULT_MEALS=[
 {id:'beef-rice-broccoli',name:'Beef, Rice & Broccoli',serving:'1 plate',calories:610,protein:48,carbs:58,fat:20,fiber:7,cost:4.25,prepMinutes:18,equipment:['stovetop','microwave'],tags:['high-protein','performance','meal-prep'],ingredients:[ingredient('Ground beef',8,'oz','Meat',2.35),ingredient('Cooked rice',1.25,'cup','Grains',.55),ingredient('Broccoli',1.5,'cup','Produce',.85),ingredient('Seasoning',1,'serving','Pantry',.15),ingredient('Cooking oil',1,'tsp','Pantry',.35)]},
 {id:'greek-yogurt-bowl',name:'Greek Yogurt Protein Bowl',serving:'1 bowl',calories:430,protein:46,carbs:48,fat:7,fiber:6,cost:3.1,prepMinutes:5,equipment:['none'],tags:['high-protein','quick','breakfast'],ingredients:[ingredient('Greek yogurt',1.5,'cup','Dairy',1.75),ingredient('Protein powder',1,'scoop','Supplements',.85),ingredient('Berries',.75,'cup','Produce',.5)]},
 {id:'chicken-rice-plate',name:'Chicken Recovery Plate',serving:'1 plate',calories:560,protein:54,carbs:62,fat:10,fiber:5,cost:4,prepMinutes:15,equipment:['air-fryer','microwave'],tags:['high-protein','low-fat','recovery'],ingredients:[ingredient('Chicken breast',8,'oz','Meat',2.25),ingredient('Cooked rice',1.5,'cup','Grains',.65),ingredient('Mixed vegetables',1,'cup','Produce',.8),ingredient('Sauce',1,'tbsp','Pantry',.3)]},
 {id:'protein-shake-banana',name:'Protein Shake & Banana',serving:'1 shake',calories:330,protein:34,carbs:43,fat:4,fiber:4,cost:2.2,prepMinutes:3,equipment:['shaker'],tags:['quick','pre-workout','high-protein'],ingredients:[ingredient('Protein powder',1.25,'scoop','Supplements',1.05),ingredient('Banana',1,'each','Produce',.35),ingredient('Milk',1,'cup','Dairy',.65),ingredient('Honey',1,'tbsp','Pantry',.15)]},
 {id:'turkey-wrap',name:'Turkey Performance Wrap',serving:'1 wrap',calories:490,protein:42,carbs:52,fat:13,fiber:8,cost:3.8,prepMinutes:8,equipment:['none'],tags:['travel','quick','high-protein'],ingredients:[ingredient('Turkey breast',6,'oz','Meat',1.9),ingredient('Whole-grain wrap',1,'each','Bakery',.65),ingredient('Cheese',1,'oz','Dairy',.55),ingredient('Spinach',1,'cup','Produce',.35),ingredient('Condiment',1,'tbsp','Pantry',.35)]},
 {id:'oats-protein',name:'Protein Oatmeal',serving:'1 bowl',calories:470,protein:38,carbs:65,fat:8,fiber:9,cost:2.35,prepMinutes:6,equipment:['microwave'],tags:['breakfast','carbs','fiber'],ingredients:[ingredient('Oats',.75,'cup','Grains',.35),ingredient('Protein powder',1,'scoop','Supplements',.85),ingredient('Milk',1,'cup','Dairy',.65),ingredient('Banana',1,'each','Produce',.35),ingredient('Cinnamon',1,'tsp','Pantry',.15)]}
];
function normalizeProfile(profile={}){return {sex:profile.sex==='female'?'female':'male',age:clamp(profile.age||35,18,90),heightIn:clamp(profile.heightIn||72,48,84),weightLb:clamp(profile.weightLb||220,80,500),bodyFat:clamp(profile.bodyFat||30,3,70),targetWeightLb:clamp(profile.targetWeightLb||200,80,500),mode:['cut','maintain','recomp','gain'].includes(profile.mode)?profile.mode:'cut',activity:['low','moderate','high','very-high'].includes(profile.activity)?profile.activity:'moderate',weeklyChangePct:clamp(profile.weeklyChangePct||0.6,0.1,1.5)};}
function leanMassLb(p){p=normalizeProfile(p);return p.weightLb*(1-p.bodyFat/100);}
function bmr(profile){const p=normalizeProfile(profile),kg=p.weightLb*.453592,cm=p.heightIn*2.54;return Math.round(10*kg+6.25*cm-5*p.age+(p.sex==='male'?5:-161));}
function targets(profile={},context={}){const p=normalizeProfile(profile),factors={low:1.3,moderate:1.5,high:1.7,'very-high':1.85};let calories=bmr(p)*factors[p.activity];const weekly=p.weightLb*(p.weeklyChangePct/100)*3500/7;if(p.mode==='cut')calories-=weekly;else if(p.mode==='gain')calories+=Math.min(weekly,450);else if(p.mode==='recomp')calories-=150;const training=context.trainingDay!==false,readiness=clamp(context.readiness||70,0,100),event=context.eventDay===true;if(training)calories+=100;if(event)calories+=250;if(readiness<50)calories-=100;calories=round(Math.max(calories,1400),25);const protein=round(Math.max(leanMassLb(p)*1,p.weightLb*.75),5);const fat=round(Math.max(p.weightLb*.28,50),5);const carbs=round(Math.max((calories-protein*4-fat*9)/4,75),5);return {calories,protein,carbs,fat,fiber:Math.max(25,round(calories/1000*14)),water:round(Math.max(96,p.weightLb*.55),8),sodium:event||training?3000:2300,potassium:3500};}
function compliance(log={},target={}){const keys=['calories','protein','carbs','fat','fiber','water'];const score=keys.reduce((sum,k)=>{const v=Number(log[k])||0,t=Number(target[k])||0;if(!t)return sum;const ratio=v/t,component=k==='calories'?Math.max(0,100-Math.abs(1-ratio)*140):Math.min(100,ratio*100);return sum+component;},0)/keys.length;return Math.round(score||0);}
function gaps(log={},target={}){return ['protein','carbs','fat','fiber','water','calories'].map(k=>({key:k,remaining:Math.max(0,round((Number(target[k])||0)-(Number(log[k])||0),k==='calories'?25:1))})).filter(x=>x.remaining>0);}
function recommendation(log={},target={},context={}){const g=Object.fromEntries(gaps(log,target).map(x=>[x.key,x.remaining]));if(g.protein>=40)return {title:'Close the protein gap',detail:`Prioritize a meal with about ${round(g.protein,5)} g protein. Pair it with a familiar carbohydrate source if training remains.`,type:'protein'};if(g.water>=24)return {title:'Hydration is the next lever',detail:`Drink ${round(Math.min(g.water,32),8)} oz over the next two hours${context.eventDay?' with electrolytes':''}.`,type:'water'};if(g.carbs>=60&&context.trainingDay!==false)return {title:'Fuel performance',detail:`Add approximately ${round(Math.min(g.carbs,80),5)} g carbohydrate around training.`,type:'carbs'};if((Number(log.calories)||0)>(Number(target.calories)||0)*1.1)return {title:'Protect the calorie target',detail:'Choose lean protein, vegetables, and calorie-free fluids for the rest of the day.',type:'calories'};return {title:'Nutrition is on course',detail:'Complete the planned meals, preserve hydration, and avoid unnecessary changes.',type:'aligned'};}
function parseIngredients(value){if(Array.isArray(value))return value.map(normalizeIngredient).filter(x=>x.name);return String(value||'').split(/\n|;/).map(line=>{const parts=line.split('|').map(x=>x.trim());return normalizeIngredient({name:parts[0],quantity:parts[1]||1,unit:parts[2]||'serving',category:parts[3]||'Other',cost:parts[4]||0});}).filter(x=>x.name);}
function normalizeIngredient(item={}){return {name:String(item.name||'').trim(),quantity:clamp(item.quantity||1,0,100000),unit:String(item.unit||'serving').trim().toLowerCase(),category:String(item.category||'Other').trim()||'Other',cost:clamp(item.cost,0,10000)};}
function normalizeMeal(meal={}){const name=String(meal.name||'Untitled meal').trim();return {id:String(meal.id||`meal-${Date.now()}-${Math.random().toString(36).slice(2,7)}`),name,serving:String(meal.serving||'1 serving').trim(),calories:clamp(meal.calories,0,5000),protein:clamp(meal.protein,0,500),carbs:clamp(meal.carbs,0,800),fat:clamp(meal.fat,0,300),fiber:clamp(meal.fiber,0,150),cost:clamp(meal.cost,0,1000),prepMinutes:clamp(meal.prepMinutes,0,1440),equipment:Array.isArray(meal.equipment)?meal.equipment.map(String):String(meal.equipment||'').split(',').map(x=>x.trim()).filter(Boolean),tags:Array.isArray(meal.tags)?meal.tags.map(String):String(meal.tags||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean),ingredients:parseIngredients(meal.ingredients),favorite:Boolean(meal.favorite),notes:String(meal.notes||'')};}
function seedMeals(library=[]){const merged=[...DEFAULT_MEALS,...(Array.isArray(library)?library:[])].map(normalizeMeal);return [...new Map(merged.map(m=>[m.id,m])).values()];}
function mealTotals(entries=[]){return (Array.isArray(entries)?entries:[]).reduce((tot,e)=>{const qty=clamp(e.quantity||1,.1,20),m=normalizeMeal(e.meal||e);MEAL_KEYS.forEach(k=>tot[k]+=m[k]*qty);tot.cost+=m.cost*qty;return tot;},{calories:0,protein:0,carbs:0,fat:0,fiber:0,cost:0});}
function remainingTargets(log={},target={}){return Object.fromEntries([...MEAL_KEYS,'water'].map(k=>[k,Math.max(0,(Number(target[k])||0)-(Number(log[k])||0))]));}
function scoreMeal(meal,remaining={},context={}){const m=normalizeMeal(meal);let score=0,calNeed=Math.max(1,remaining.calories||1);score+=Math.min(m.protein,remaining.protein||0)*2.4;score+=Math.min(m.carbs,remaining.carbs||0)*(context.trainingDay!==false?1.05:.55);score+=Math.min(m.fiber,remaining.fiber||0)*2;score-=Math.max(0,m.calories-calNeed)*.12;score-=m.cost*1.5;score-=Math.max(0,m.prepMinutes-(context.maxPrepMinutes||30))*.8;if(m.favorite)score+=12;if(context.maxPrepMinutes!=null&&m.prepMinutes<=context.maxPrepMinutes)score+=8;return Math.round(score);}
function rankMeals(library=[],log={},target={},context={}){const remaining=remainingTargets(log,target);return seedMeals(library).map(meal=>({...meal,matchScore:scoreMeal(meal,remaining,context)})).sort((a,b)=>b.matchScore-a.matchScore);}
function mealSuggestion(log={},target={},library=[],context={}){return rankMeals(library,log,target,{trainingDay:true,...context})[0]||normalizeMeal(DEFAULT_MEALS[0]);}
function normalizePrepPlan(plan=[]){return (Array.isArray(plan)?plan:[]).map(x=>({mealId:String(x.mealId||''),servings:clamp(x.servings||1,1,50)})).filter(x=>x.mealId);}
function groceryList(plan=[],library=[],pantry={}){const meals=new Map(seedMeals(library).map(m=>[m.id,m])),items=new Map();normalizePrepPlan(plan).forEach(p=>{const meal=meals.get(p.mealId);if(!meal)return;meal.ingredients.forEach(raw=>{const ing=normalizeIngredient(raw),key=`${ing.name.toLowerCase()}|${ing.unit}`;if(!items.has(key))items.set(key,{...ing,quantity:0,cost:0,mealIds:[]});const item=items.get(key);item.quantity+=ing.quantity*p.servings;item.cost+=ing.cost*p.servings;if(!item.mealIds.includes(meal.id))item.mealIds.push(meal.id);});});return [...items.values()].map(item=>{const have=clamp(pantry[item.name.toLowerCase()]||0,0,100000),needed=Math.max(0,item.quantity-have);return {...item,quantity:round(item.quantity,.01),pantryQuantity:have,needed:round(needed,.01),estimatedCost:item.quantity?round(item.cost*(needed/item.quantity),.01):0};}).filter(x=>x.needed>0).sort((a,b)=>a.category.localeCompare(b.category)||a.name.localeCompare(b.name));}
function prepSummary(plan=[],library=[],pantry={}){const normalized=normalizePrepPlan(plan),meals=new Map(seedMeals(library).map(m=>[m.id,m])),servings=normalized.reduce((s,p)=>s+p.servings,0),minutes=normalized.reduce((s,p)=>s+(meals.get(p.mealId)?.prepMinutes||0),0),cost=normalized.reduce((s,p)=>s+(meals.get(p.mealId)?.cost||0)*p.servings,0),groceries=groceryList(normalized,library,pantry);return {meals:normalized.length,servings,prepMinutes:minutes,estimatedCost:round(cost,.01),shoppingCost:round(groceries.reduce((s,x)=>s+x.estimatedCost,0),.01),groceries};}
return {DEFAULT_MEALS,normalizeProfile,leanMassLb,bmr,targets,compliance,gaps,recommendation,normalizeIngredient,parseIngredients,normalizeMeal,seedMeals,mealTotals,remainingTargets,scoreMeal,rankMeals,mealSuggestion,normalizePrepPlan,groceryList,prepSummary};
});
