(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.TrainingCoach=api;})(typeof window!=='undefined'?window:globalThis,function(){
'use strict';
const VERSION='2.4.0';
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const clone=v=>JSON.parse(JSON.stringify(v));
const completed=s=>(s||[]).filter(x=>x.status==='completed');
function editWorkout(workout,patch={}){const next=clone(workout||{});Object.assign(next,patch);next.exercises=(patch.exercises||next.exercises||[]).map((x,i)=>({...x,order:i}));next.updatedAt=new Date().toISOString();return next;}
function moveExercise(exercises,from,to){const next=clone(exercises||[]);if(from<0||to<0||from>=next.length||to>=next.length)return next;const [item]=next.splice(from,1);next.splice(to,0,item);return next.map((x,i)=>({...x,order:i}));}
function removeExercise(exercises,index){return clone(exercises||[]).filter((_,i)=>i!==index).map((x,i)=>({...x,order:i}));}
function muscleVolume(sessions,library,days=7){const cutoff=Date.now()-days*864e5,map=new Map((library||[]).map(x=>[x.id,x]));const totals={};completed(sessions).filter(s=>new Date(s.completedAt||s.date).getTime()>=cutoff).forEach(s=>(s.exercises||[]).forEach(ex=>{const lib=map.get(ex.exerciseId)||{};const muscles=[...(lib.primaryMuscles||[]),...(lib.secondaryMuscles||[]).map(x=>`Secondary: ${x}`)];const volume=(ex.sets||[]).filter(x=>x.completed).reduce((a,x)=>a+n(x.weight)*n(x.reps),0);muscles.forEach((m,i)=>totals[m]=(totals[m]||0)+volume*(i&&m.startsWith('Secondary:')?.5:1));}));return Object.entries(totals).map(([muscle,volume])=>({muscle,volume:Math.round(volume)})).sort((a,b)=>b.volume-a.volume);}
function weeklyLoad(sessions,days=7){const cutoff=Date.now()-days*864e5;const rows=completed(sessions).filter(s=>new Date(s.completedAt||s.date).getTime()>=cutoff);const load=rows.reduce((sum,s)=>sum+n(s.durationMinutes)*(n(s.metrics?.avgRpe)||5),0);return{sessions:rows.length,minutes:rows.reduce((a,s)=>a+n(s.durationMinutes),0),load:Math.round(load)};}
function recoveryScore(sessions,readiness={}){const recent=completed(sessions).slice().sort((a,b)=>String(b.completedAt||b.date).localeCompare(String(a.completedAt||a.date))).slice(0,4);const avgRpe=recent.length?recent.reduce((a,s)=>a+n(s.metrics?.avgRpe),0)/recent.length:5;const daysSince=recent[0]?Math.max(0,(Date.now()-new Date(recent[0].completedAt||recent[0].date).getTime())/864e5):3;let score=70+(daysSince*6)-Math.max(0,avgRpe-7)*8;score+=((n(readiness.sleep)||7)-7)*4;score-=n(readiness.soreness)*4;score-=n(readiness.pain)*8;return Math.max(0,Math.min(100,Math.round(score)));}
function progression(exerciseId,sessions){const rows=completed(sessions).slice().sort((a,b)=>String(a.completedAt||a.date).localeCompare(String(b.completedAt||b.date))).map(s=>(s.exercises||[]).find(e=>e.exerciseId===exerciseId)).filter(Boolean);if(!rows.length)return{action:'start',label:'Establish baseline',detail:'Complete the exercise once before progressing.'};const latest=rows.at(-1),sets=(latest.sets||[]).filter(x=>x.completed),completion=sets.length/Math.max(1,n(latest.targetSets)||sets.length),avgRpe=sets.length?sets.reduce((a,x)=>a+n(x.rpe),0)/sets.length:10;if(completion>=1&&avgRpe<=7.5)return{action:'increase',label:'Increase load',detail:'Add 2.5–5% next time while keeping the same rep target.'};if(completion>=.8&&avgRpe<=9)return{action:'hold',label:'Repeat load',detail:'Keep the load and aim to complete every prescribed rep.'};if(avgRpe>9||completion<.65)return{action:'reduce',label:'Reduce or deload',detail:'Lower load 5–10% or remove one set for the next exposure.'};return{action:'repeat',label:'Repeat and refine',detail:'Keep the prescription and improve technique or rep quality.'};}
function exerciseHistory(exerciseId,sessions){return completed(sessions).map(s=>{const ex=(s.exercises||[]).find(e=>e.exerciseId===exerciseId);if(!ex)return null;const sets=(ex.sets||[]).filter(x=>x.completed);return{date:String(s.completedAt||s.date||'').slice(0,10),weight:Math.max(0,...sets.map(x=>n(x.weight))),reps:Math.max(0,...sets.map(x=>n(x.reps))),volume:sets.reduce((a,x)=>a+n(x.weight)*n(x.reps),0),avgRpe:sets.length?Math.round(sets.reduce((a,x)=>a+n(x.rpe),0)/sets.length*10)/10:0};}).filter(Boolean).sort((a,b)=>b.date.localeCompare(a.date));}
function prDashboard(records){const rows=(records||[]).slice().sort((a,b)=>String(b.date).localeCompare(String(a.date)));const byType={};rows.forEach(r=>{const k=r.type||'record';byType[k]=(byType[k]||0)+1;});return{total:rows.length,automatic:rows.filter(x=>x.source==='automatic').length,recent:rows.slice(0,10),byType};}
return{VERSION,editWorkout,moveExercise,removeExercise,muscleVolume,weeklyLoad,recoveryScore,progression,exerciseHistory,prDashboard};
});
