const assert=require('assert');
const N=require('../src/modules/nutrition-system.js');
const library=N.seedMeals([]);
const beef=library.find(m=>m.id==='beef-rice-broccoli');
assert(beef&&beef.ingredients.length>=3,'seeded meals should include structured ingredients');
const custom=N.normalizeMeal({name:'Custom',ingredients:'Chicken | 8 | oz | Meat | 2.00\nRice | 1 | cup | Grains | 0.50'});
assert.strictEqual(custom.ingredients.length,2);
assert.strictEqual(custom.ingredients[0].quantity,8);
const plan=[{mealId:'beef-rice-broccoli',servings:4},{mealId:'protein-shake-banana',servings:2}];
const list=N.groceryList(plan,library,{});
const groundBeef=list.find(x=>x.name==='Ground beef');
assert(groundBeef,'grocery list should contain meal ingredients');
assert.strictEqual(groundBeef.needed,32);
const pantryList=N.groceryList(plan,library,{'ground beef':16});
assert.strictEqual(pantryList.find(x=>x.name==='Ground beef').needed,16,'pantry quantity should reduce shopping need');
const summary=N.prepSummary(plan,library,{});
assert.strictEqual(summary.meals,2);
assert.strictEqual(summary.servings,6);
assert(summary.shoppingCost>0);
assert(summary.groceries.length>0);
console.log('Nutrition grocery intelligence tests passed');
