/* Iron Disciple OS — Phase 2.3 Session Execution & History */
(()=>{'use strict';const P=window.TrainingSessionPro;if(!P)return;
function persist(){localStorage.setItem(KEY,JSON.stringify(state));}
function migrate(){state.version='2.3.0';state.training=state.training||{};state.training.sessionPro={schemaVersion:1,historyFilter:'all',...(state.training.sessionPro||{})};const m=state.os?.modules?.find(x=>x.id==='training');if(m){m.version=P.VERSION;m.capabilities=[...new Set([...(m.capabilities||[]),'exercise-substitution','session-history','group-execution','completion-progress'])];}}
function inject(){const panel=document.querySelector('[data-body-panel="training"]');if(panel&&!document.querySelector('#trainingHistory'))panel.insertAdjacentHTML('beforeend','<section class="section-block"><div class="section-head"><div><span class="kicker">HISTORY</span><h3>Completed Sessions</h3></div><select id="trainingHistoryFilter"><option value="all">All sessions</option><option value="30">Last 30 days</option><option value="7">Last 7 days</option></select></div><div id="trainingHistory" class="card-list"></div></section>');
const tools=document.querySelector('#trainingSessionTools');if(tools&&!document.querySelector('#sessionProgress'))tools.insertAdjacentHTML('afterbegin','<div class="session-progress-wrap"><div><strong id="sessionProgress">0% complete</strong><small id="sessionProgressDetail">0 of 0 sets</small></div><div class="bar"><i id="sessionProgressBar" style="width:0%"></i></div></div>');}
function history(){let items=P.sessionHistory(state.training.sessions);const f=document.querySelector('#trainingHistoryFilter')?.value||state.training.sessionPro.historyFilter||'all';state.training.sessionPro.historyFilter=f;if(f!=='all'){const cutoff=Date.now()-Number(f)*864e5;items=items.filter(x=>new Date(x.date).getTime()>=cutoff);}const box=document.querySelector('#trainingHistory');if(!box)return;box.innerHTML=items.map(x=>`<article class="list-card training-history-card"><div class="grow"><small>${esc(x.date)} · ${x.durationMinutes} min · RPE ${x.avgRpe||0}</small><strong>${esc(x.name)}</strong><p>${x.sets} sets · ${x.reps} reps · ${x.volume.toLocaleString()} volume${x.notes?` · ${esc(x.notes)}`:''}</p></div></article>`).join('')||empty('Completed workouts will appear here.');persist();}
function enhanceSession(){const s=state.training.sessions.find(x=>x.id===state.training.activeSessionId);if(!s)return;const prog=P.completionProgress(s),a=document.querySelector('#sessionProgress'),b=document.querySelector('#sessionProgressDetail'),bar=document.querySelector('#sessionProgressBar');if(a)a.textContent=`${prog.percent}% complete`;if(b)b.textContent=`${prog.complete} of ${prog.total} sets`;if(bar)bar.style.width=`${prog.percent}%`;document.querySelectorAll('#sessionExerciseList [data-session-exercise]').forEach((el,i)=>{if(el.querySelector('[data-substitute-session]'))return;const ex=s.exercises[i];const choices=state.exerciseLibrary.filter(x=>x.id!==ex.exerciseId).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');el.querySelector('.section-head')?.insertAdjacentHTML('beforeend',`<div class="session-exercise-actions"><select data-substitute-select="${i}"><option value="">Substitute…</option>${choices}</select><button class="mini-btn" type="button" data-substitute-session="${i}">Apply</button></div>`);});}
function substitute(index){const s=state.training.sessions.find(x=>x.id===state.training.activeSessionId);const select=document.querySelector(`[data-substitute-select="${index}"]`);const replacement=state.exerciseLibrary.find(x=>x.id===select?.value);if(!s||!replacement)return;const ex=s.exercises[index];ex.exerciseId=replacement.id;ex.name=replacement.name;const w=state.workouts.find(x=>x.id===s.workoutId);if(w){w.exercises=P.substituteExercise(w,w.exercises[index]?.exerciseId,replacement).exercises;}persist();const dialog=document.querySelector('#trainingSessionDialog');dialog?.close();document.querySelector(`[data-start-training="${s.workoutId}"]`)?.click();}
function bind(){document.addEventListener('click',e=>{const b=e.target.closest('[data-substitute-session]');if(b)substitute(Number(b.dataset.substituteSession));});document.addEventListener('change',e=>{if(e.target.matches('#trainingSessionDialog [data-set-field="completed"]'))setTimeout(enhanceSession,0);if(e.target.id==='trainingHistoryFilter')history();});}
migrate();inject();bind();const prior=render;render=function training23Render(){prior();history();enhanceSession();const v=document.querySelector('[data-view="more"] .version');if(v)v.textContent='Iron Disciple OS 2.3.0 — Training Execution & History';};persist();render();})();
