/* Iron Disciple OS — Phase 2.1 Training Foundation */
(() => {
  'use strict';
  const T=window.TrainingSystem;if(!T)return;
  const nowIso=()=>new Date().toISOString();
  let builderDraft=[];

  function migrate(){
    const migrated=T.migrateTrainingState(state);Object.keys(state).forEach(k=>delete state[k]);Object.assign(state,migrated);
    state.version='2.1.0';
    state.personalRecords=(state.personalRecords||[]).map(r=>({id:r.id||id(),date:r.date||todayKey(),exerciseId:r.exerciseId||'',exercise:r.exercise||'Exercise',type:r.type||'manual',value:r.value,unit:r.unit||'lb',note:r.note||'',source:r.source||'manual',sessionId:r.sessionId||null}));
    try{state.os=state.os||{};state.os.modules=Array.isArray(state.os.modules)?state.os.modules:[];const definition={id:'training',name:'Training',view:'body',status:'active',icon:'△',version:T.VERSION,capabilities:['exercise-library','workout-builder','live-logging','personal-records','progression'],taskTypes:['workout','mobility','recovery'],registeredAt:nowIso()};const module=window.IDOSPlatformKernel?.normalizeModule?window.IDOSPlatformKernel.normalizeModule(definition):definition;const index=state.os.modules.findIndex(x=>x.id==='training');if(index>=0)state.os.modules[index]=module;else state.os.modules.push(module);}catch{}
  }
  function inject(){
    const panel=document.querySelector('[data-body-panel="training"]');if(!panel||document.querySelector('#trainingStats'))return;
    const toolbar=panel.querySelector('.goal-toolbar');toolbar.insertAdjacentHTML('afterend','<section id="trainingStats" class="metric-grid training-stat-grid"></section><section class="training-controls"><input id="trainingSearch" type="search" placeholder="Search exercises"><select id="trainingCategory"><option value="all">All categories</option></select><button id="startNextWorkout" class="secondary-btn" type="button">Start Next Workout</button></section>');
    document.body.insertAdjacentHTML('beforeend',`<dialog id="workoutBuilderDialog" class="app-dialog training-dialog"><form method="dialog" class="dialog-shell" id="workoutBuilderForm"><div class="dialog-head"><div><span class="kicker">TRAINING BUILDER</span><h3>Build Workout</h3></div><button value="cancel" class="icon-btn" aria-label="Close">×</button></div><div class="form-card two-col"><label>Date<input id="builderDate" type="date" required></label><label>Name<input id="builderName" required placeholder="Upper Body Strength"></label><label>Type<select id="builderType"><option>Strength</option><option>Hypertrophy</option><option>Power</option><option>Conditioning</option><option>Mobility</option><option>Recovery</option><option>Tournament Prep</option><option>Deload</option></select></label><label>Add exercise<select id="builderExercise"></select></label><div class="builder-prescription span-2"><label>Sets<input id="builderSets" type="number" min="1" value="3"></label><label>Reps<input id="builderReps" value="10"></label><label>Load<input id="builderLoad" placeholder="30 lb or heavy band"></label><label>Rest seconds<input id="builderRest" type="number" min="0" value="90"></label><button id="builderAddExercise" class="secondary-btn" type="button">Add Exercise</button></div><div id="builderExerciseList" class="span-2 workout-list"></div><button id="saveBuiltWorkout" class="primary-btn span-2" type="button">Save Workout</button></div></form></dialog>
    <dialog id="trainingSessionDialog" class="app-dialog training-dialog"><div class="dialog-shell"><div class="dialog-head"><div><span class="kicker">LIVE SESSION</span><h3 id="sessionTitle">Workout</h3><small id="sessionMeta"></small></div><button id="closeTrainingSession" class="icon-btn" aria-label="Close">×</button></div><div id="sessionExerciseList" class="session-exercise-list"></div><label class="form-card">Session notes<textarea id="sessionNotes"></textarea></label><div class="dialog-actions"><button id="saveTrainingSession" class="secondary-btn" type="button">Save & Close</button><button id="finishTrainingSession" class="primary-btn" type="button">Finish Workout</button></div></div></dialog>
    <dialog id="exerciseDetailDialog" class="app-dialog training-dialog"><div class="dialog-shell"><div class="dialog-head"><div><span class="kicker">EXERCISE</span><h3 id="exerciseDetailTitle"></h3></div><button id="closeExerciseDetail" class="icon-btn">×</button></div><div id="exerciseDetailBody"></div></div></dialog>`);
  }
  const workoutFor=idValue=>state.workouts.find(w=>w.id===idValue);
  const sessionsFor=idValue=>state.training.sessions.filter(s=>s.workoutId===idValue&&s.status==='completed');
  function latestRecommendation(workout){
    const session=sessionsFor(workout.id).slice(-1)[0];if(!session)return null;const metrics=T.sessionMetrics(session);const target=workout.exercises.reduce((sum,x)=>sum+Number(x.sets||0),0);return T.progressionRecommendation({targetSets:target,completedSets:metrics.sets,averageRpe:metrics.avgRpe,pain:session.pain||0,technique:session.technique||8});
  }
  function renderStats(){
    const sessions=state.training.sessions.filter(x=>x.status==='completed'),last=sessions.slice(-1)[0],metrics=last?T.sessionMetrics(last):null,week=new Date(Date.now()-7*864e5).toISOString().slice(0,10),weekly=sessions.filter(x=>String(x.completedAt||x.date)>=week);
    $('#trainingStats').innerHTML=[[state.exerciseLibrary.length,'Exercises','Structured library'],[state.workouts.filter(x=>!x.done).length,'Planned','Open workouts'],[weekly.length,'Sessions','Last 7 days'],[metrics?metrics.totalVolume.toLocaleString():'0','Last volume','lb × reps']].map(([v,k,d])=>`<article class="review-card"><span class="kicker">${esc(k)}</span><strong>${esc(v)}</strong><small>${esc(d)}</small></article>`).join('');
  }
  function renderWorkouts(){
    $('#workoutList').innerHTML=state.workouts.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(w=>{const rec=latestRecommendation(w);const session=sessionsFor(w.id).slice(-1)[0],metrics=session?T.sessionMetrics(session):null;return `<article class="workout-card ${w.done?'complete':''}" data-training-workout="${w.id}"><div class="project-top"><div><small>${esc(w.date||todayKey())} · ${esc(w.type||'Training')}</small><strong>${esc(w.name)}</strong></div><button class="icon-btn" data-delete="workouts" data-id="${w.id}">×</button></div><div class="exercise-lines">${(w.exercises||[]).map((e,i)=>`<div class="exercise-line"><span>${i+1}</span><div><strong>${esc(e.name)}</strong><small>${esc(e.sets)} × ${esc(e.reps)}${e.load?` · ${esc(e.load)}`:''} · ${e.restSeconds||90}s</small></div></div>`).join('')||'<small>No exercises added.</small>'}</div>${metrics?`<div class="training-session-summary"><span>${metrics.sets} sets</span><span>${metrics.totalReps} reps</span><span>${metrics.totalVolume.toLocaleString()} volume</span><span>RPE ${metrics.avgRpe||0}</span></div>`:''}${rec?`<div class="training-recommendation ${rec.action}"><strong>${rec.label}</strong><span>${esc(rec.detail)}</span></div>`:''}<div class="workout-actions"><button class="primary-btn small" data-start-training="${w.id}">${session?'Repeat / Review':'Start Workout'}</button><label class="check-row"><input type="checkbox" data-workout-toggle="${w.id}" ${w.done?'checked':''}><span>Complete</span></label></div></article>`}).join('')||empty('Create your first structured workout.');
  }
  function renderExercises(){
    const q=($('#trainingSearch')?.value||'').toLowerCase(),cat=$('#trainingCategory')?.value||'all';const categories=[...new Set(state.exerciseLibrary.map(x=>x.category))].sort();const select=$('#trainingCategory');if(select&&select.options.length!==categories.length+1){select.innerHTML='<option value="all">All categories</option>'+categories.map(x=>`<option>${esc(x)}</option>`).join('');select.value=cat;}
    const items=state.exerciseLibrary.filter(e=>(cat==='all'||e.category===cat)&&`${e.name} ${e.category} ${e.movement} ${(e.primaryMuscles||[]).join(' ')}`.toLowerCase().includes(q));
    $('#exerciseLibrary').innerHTML=items.map(e=>`<article class="exercise-card"><div><small>${esc(e.category)} · ${esc(e.movement)}</small><strong>${esc(e.name)}</strong><p>${esc(e.instructions)}</p><div class="exercise-tags">${(e.equipment||[]).slice(0,2).map(x=>`<span>${esc(x)}</span>`).join('')}</div></div><div class="exercise-card-actions"><button class="mini-btn" data-exercise-detail="${e.id}">Details</button>${e.custom?`<button class="icon-btn" data-delete="exerciseLibrary" data-id="${e.id}">×</button>`:''}</div></article>`).join('')||empty('No exercises match the filter.');
  }
  function renderRecords(){
    $('#prList').innerHTML=state.personalRecords.slice().reverse().map(r=>`<div class="list-card"><div><small>${esc(r.date)} · ${esc(r.exercise)} · ${esc(String(r.type||'record').replaceAll('-',' '))}</small><strong>${esc(r.value)} ${esc(r.unit||'lb')}</strong><p>${esc(r.note|| (r.source==='automatic'?'Detected automatically from a completed session.':''))}</p></div><button class="icon-btn" data-delete="personalRecords" data-id="${r.id}">×</button></div>`).join('')||empty('Personal records will be detected automatically when workouts are completed.');
  }
  function renderTraining(){renderStats();renderWorkouts();renderExercises();renderRecords();bindBodyDynamic();bindDynamic();const version=document.querySelector('[data-view="more"] .version');if(version)version.textContent='Iron Disciple OS 2.1.0 — Training Foundation';}
  function openBuilder(){
    builderDraft=[];$('#builderDate').value=todayKey();$('#builderName').value='';$('#builderType').value='Strength';$('#builderExercise').innerHTML=state.exerciseLibrary.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('');renderBuilderDraft();$('#workoutBuilderDialog').showModal();
  }
  function renderBuilderDraft(){$('#builderExerciseList').innerHTML=builderDraft.map((e,i)=>`<div class="list-card"><div><strong>${esc(e.name)}</strong><small>${e.sets} × ${esc(e.reps)} · ${esc(e.load||'unloaded')} · ${e.restSeconds}s</small></div><button class="icon-btn" data-builder-remove="${i}">×</button></div>`).join('')||empty('Add exercises from the library.');}
  function addBuilderExercise(){const exercise=state.exerciseLibrary.find(e=>e.id===$('#builderExercise').value);if(!exercise)return;builderDraft.push({id:id(),exerciseId:exercise.id,name:exercise.name,sets:Math.max(1,Number($('#builderSets').value||3)),reps:$('#builderReps').value||'10',load:$('#builderLoad').value.trim(),restSeconds:Math.max(0,Number($('#builderRest').value||90)),tempo:'controlled',notes:''});renderBuilderDraft();}
  function saveBuiltWorkout(){const name=$('#builderName').value.trim();if(!name||!builderDraft.length)return alert('Enter a workout name and add at least one exercise.');state.workouts.push({id:id(),date:$('#builderDate').value||todayKey(),name,type:$('#builderType').value,exercises:builderDraft.map(x=>({...x})),done:false,createdAt:nowIso(),updatedAt:nowIso()});$('#workoutBuilderDialog').close();save();}
  function createSession(workout){return{id:id(),workoutId:workout.id,workoutName:workout.name,date:todayKey(),status:'active',startedAt:nowIso(),completedAt:null,durationMinutes:0,notes:'',technique:8,pain:0,exercises:workout.exercises.map(e=>({exerciseId:e.exerciseId,name:e.name,targetSets:Number(e.sets||3),targetReps:e.reps,sets:Array.from({length:Number(e.sets||3)},()=>({weight:Number.parseFloat(e.load)||0,reps:0,rpe:8,completed:false}))}))};}
  function openSession(workoutId){const workout=workoutFor(workoutId);if(!workout)return;let session=state.training.sessions.find(s=>s.workoutId===workoutId&&s.status==='active');if(!session){session=createSession(workout);state.training.sessions.push(session);}state.training.activeSessionId=session.id;localStorage.setItem(KEY,JSON.stringify(state));renderSession(session,workout);$('#trainingSessionDialog').showModal();}
  function activeSession(){return state.training.sessions.find(s=>s.id===state.training.activeSessionId);}
  function renderSession(session,workout){$('#sessionTitle').textContent=workout.name;$('#sessionMeta').textContent=`${workout.type} · ${workout.exercises.length} exercises · started ${new Date(session.startedAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}`;$('#sessionNotes').value=session.notes||'';$('#sessionExerciseList').innerHTML=session.exercises.map((ex,exIndex)=>{const library=state.exerciseLibrary.find(x=>x.id===ex.exerciseId);return `<section class="session-exercise" data-session-exercise="${exIndex}"><div class="section-head"><div><span class="kicker">${esc(library?.movement||'Exercise')}</span><h3>${esc(ex.name)}</h3><small>${ex.targetSets} sets · target ${esc(ex.targetReps)} reps</small></div><button class="mini-btn" data-exercise-detail="${ex.exerciseId}">Technique</button></div><div class="session-set-head"><span>Set</span><span>Weight</span><span>Reps</span><span>RPE</span><span>Done</span></div>${ex.sets.map((set,setIndex)=>`<div class="session-set" data-session-set="${setIndex}"><strong>${setIndex+1}</strong><input data-set-field="weight" type="number" min="0" step="1" value="${set.weight||''}"><input data-set-field="reps" type="number" min="0" max="100" value="${set.reps||''}"><input data-set-field="rpe" type="number" min="1" max="10" step=".5" value="${set.rpe||8}"><input data-set-field="completed" type="checkbox" ${set.completed?'checked':''}></div>`).join('')}</section>`}).join('');}
  function syncSession(){const session=activeSession();if(!session)return;session.notes=$('#sessionNotes').value;$$('[data-session-exercise]').forEach(exEl=>{const ex=session.exercises[Number(exEl.dataset.sessionExercise)];exEl.querySelectorAll('[data-session-set]').forEach(setEl=>{const set=ex.sets[Number(setEl.dataset.sessionSet)];setEl.querySelectorAll('[data-set-field]').forEach(input=>{set[input.dataset.setField]=input.type==='checkbox'?input.checked:Number(input.value||0);});});});localStorage.setItem(KEY,JSON.stringify(state));}
  function finishSession(){const session=activeSession();if(!session)return;syncSession();const metrics=T.sessionMetrics(session);if(!metrics.sets)return alert('Log at least one completed set before finishing.');const prior=state.training.sessions.filter(s=>s.id!==session.id&&s.status==='completed');const records=T.recordsForSession(session,prior);session.status='completed';session.completedAt=nowIso();session.durationMinutes=Math.max(1,Math.round((new Date(session.completedAt)-new Date(session.startedAt))/60000));session.metrics=T.sessionMetrics(session);records.forEach(r=>state.personalRecords.push({id:id(),date:todayKey(),...r,note:'',source:'automatic',sessionId:session.id}));const workout=workoutFor(session.workoutId);if(workout)workout.done=true;state.workout=workout?{name:workout.name,detail:`${session.metrics.sets} sets · ${session.metrics.totalVolume} volume`,done:true}:state.workout;state.training.activeSessionId=null;try{state.os=state.os||{};state.os.activity=Array.isArray(state.os.activity)?state.os.activity:[];state.os.activity.push({id:id(),type:'training.session.completed',module:'training',title:session.workoutName,detail:{sessionId:session.id,records:records.length,metrics:session.metrics},timestamp:nowIso()});}catch{}$('#trainingSessionDialog').close();save();if(records.length)alert(`${records.length} new personal record${records.length===1?'':'s'} detected.`);}
  function exerciseDetail(exerciseId){const e=state.exerciseLibrary.find(x=>x.id===exerciseId);if(!e)return;$('#exerciseDetailTitle').textContent=e.name;const section=(title,items)=>items?.length?`<section class="form-card"><span class="kicker">${title}</span><ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`:'';$('#exerciseDetailBody').innerHTML=`<section class="exercise-detail-hero"><p>${esc(e.instructions)}</p><div class="exercise-tags"><span>${esc(e.category)}</span><span>${esc(e.difficulty)}</span>${(e.equipment||[]).map(x=>`<span>${esc(x)}</span>`).join('')}</div></section>${section('PRIMARY MUSCLES',e.primaryMuscles)}${section('COACHING CUES',e.cues)}${section('COMMON MISTAKES',e.commonMistakes)}${section('ALTERNATIVES',e.alternatives)}`;$('#exerciseDetailDialog').showModal();}
  function bind(){
    $('#createWorkout').onclick=openBuilder;$('#addExercise').onclick=()=>openModal('Add Exercise','<label>Name<input name="name" required></label><label>Category<input name="category" placeholder="Upper Body"></label><label>Movement pattern<input name="movement" placeholder="Horizontal push"></label><label>Equipment<input name="equipment" placeholder="Bands, dumbbells"></label><label>Primary muscles<input name="primaryMuscles"></label><label>Instructions<textarea name="instructions"></textarea></label><label>Coaching cues<input name="cues" placeholder="Separate cues with commas"></label><label>Common mistakes<input name="commonMistakes" placeholder="Separate with commas"></label>',d=>state.exerciseLibrary.push(T.normalizeExercise({id:id(),...d,custom:true})));
    $('#builderAddExercise').onclick=addBuilderExercise;$('#saveBuiltWorkout').onclick=saveBuiltWorkout;$('#startNextWorkout').onclick=()=>{const next=state.workouts.find(w=>!w.done&&w.date===todayKey())||state.workouts.find(w=>!w.done);if(next)openSession(next.id);else openBuilder();};
    $('#trainingSearch').oninput=renderExercises;$('#trainingCategory').onchange=renderExercises;$('#closeTrainingSession').onclick=()=>{syncSession();$('#trainingSessionDialog').close();};$('#saveTrainingSession').onclick=()=>{syncSession();$('#trainingSessionDialog').close();save();};$('#finishTrainingSession').onclick=finishSession;$('#closeExerciseDetail').onclick=()=>$('#exerciseDetailDialog').close();
    document.addEventListener('click',event=>{const start=event.target.closest('[data-start-training]');if(start)openSession(start.dataset.startTraining);const detail=event.target.closest('[data-exercise-detail]');if(detail)exerciseDetail(detail.dataset.exerciseDetail);const remove=event.target.closest('[data-builder-remove]');if(remove){builderDraft.splice(Number(remove.dataset.builderRemove),1);renderBuilderDraft();}});
    $('#trainingSessionDialog').addEventListener('change',syncSession);
  }
  migrate();inject();bind();const priorRender=render;render=function trainingRender(){priorRender();renderTraining();};localStorage.setItem(KEY,JSON.stringify(state));render();
})();
